dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"

    // Fabric API
    modImplementation("net.fabricmc.fabric-api:fabric-api:$rootProject.fabric_api_version") {
        exclude group: "net.fabricmc.fabric-api", module: "fabric-content-registries-v0"
    }

    modApi "com.terraformersmc:modmenu:${project.modmenu}"
    implementation project(':common')
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

jar {
    from project(':common').sourceSets.main.output
}

sourcesJar {
    from project(':common').sourceSets.main.allSource
}
