# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
# Mod properties
mod_version = 1.0.0
maven_group = pro.mikey.autoclicker
archives_name = MultiClicker
enabled_platforms = fabric

# Minecraft properties
minecraft_version = 26.1

# Dependencies
fabric_loader_version=0.16.14
fabric_api_version=0.145.1+26.1
neoforge_version = 21.6.20-beta

modmenu = 18.0.2

# curseforge_id=
# modrinth_id=

# Loom settings
loom.allowMismatchedPlatformVersion=true
loom.ignoreDependencyLoomVersionValidation=true
