fabric_api_version = 0.58.0+1.19
modmenu = 4.0.6
compat = base,until_1_21_5,until_1_21_4,until_1_21_1,until_1_20_6,until_1_20_4,until_1_20_1,until_1_19_4,until_1_19_3,until_1_19_2
java_version = 17
forge_version = 1.19-41.1.0
