modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "multiclicker"
version = "${version}"
displayName = "Multi Clicker"
authors = "Multi Clicker Team"
description = '''
Automatically left and right clicks for you, how kind!
'''
logoFile = "assets/multiclicker/icon.png"

[[dependencies.multiclicker]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.multiclicker]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "multiclicker.mixins.json"
